version: "3"
services:
  react-client:
    stdin_open: true
    image: react-client
    build:
      context: react-client
      dockerfile: Dockerfile
    volumes:
      - ./react-client/src:/app/src
      - ./react-client/node_modules:/app/node_modules
      - ./react-client/wasm:/app/wasm
    depends_on:
      - wasm-base
  wasm-base:
    image: wasm-base
    build:
      context: react-client/wasm
      dockerfile: Dockerfile
    volumes:
      - ./react-client/wasm:/app/wasm
  nginx-gateway:
    restart: always
    depends_on:
      - react-client
    build:
      context: ./nginx-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:80"
